---

- name: Install web servers
  hosts: linux
  remote_user: fedora
  become: true
#  debugger: always

  handlers:
  - import_tasks: ../handlers/main.yml

  tasks:
  - include_vars: ../vars/main.yml

  - name: "Monstrar mensaje condicional"
    debug:
      msg: "Se va a ejecutar el playbook sobre un sistema operativo Fedora"
    when: ansible_facts['distribution'] == "Fedora"

  - name: "Instalar Apache"
    yum:
      name: "{{ item }}"  
      state: present
    loop: "{{ packages }}"

  - name: "Create document root"
    file:
      path: "/var/www/{{ http_dir }}"
      state: directory

  - name: "Copy source code"
    copy:
      src: "{{ source_code_location }}index.html"
      dest: "/var/www/{{ http_dir }}"

  - name: "Copy conf file"
    template:
      src: "../templates/apache.conf.j2"
      dest: "/etc/httpd/conf.d/apache.conf"
    notify: "Restart httpd"

  - name: "Enable HTTP"
    service:
      name: "httpd"
      enabled: yes

  - name: "Start Apache service"
    service:
      name: "httpd"
      state: started

  - name: "Enable Firewalld"
    service: 
      name: "firewalld"
      enabled: yes
  
  - name: "Start Firewall Service"
    service:
      name: "firewalld"
      state: started

  - name: "Add firewall rules"
    firewalld:
      port: "{{ http_port }}/tcp"
      permanent: yes
      state: enabled
      immediate: yes
    notify: "Restart firewalld"
